-- Migration : Insertion de la véritable légion de citations (V4)
-- On laisse PostgreSQL gérer les IDs pour éviter tout conflit de format.

INSERT INTO public.quotes (text, author, source, category, aura_level, background_image)
VALUES
  ('Ce qui ne me tue pas me rend plus fort.', 'Friedrich Nietzsche', 'Réalité', 'Mental', 98, NULL),
  ('Le guerrier le plus puissant est celui qui se bat avec lui-même et gagne.', 'Miyamoto Musashi', 'Vagabond', 'Discipline', 100, NULL),
  ('La discipline, c’est choisir entre ce que tu veux maintenant et ce que tu veux le plus.', 'Abraham Lincoln', 'Réalité', 'Discipline', 95, NULL),
  ('Si tu traverses l''enfer, continue d''avancer.', 'Winston Churchill', 'Réalité', 'Ambition', 97, NULL),
  ('Je n''ai jamais perdu. Soit je gagne, soit j''apprends.', 'Nelson Mandela', 'Réalité', 'Mental', 94, NULL),
  ('Pour devenir le meilleur, tu dois être capable de supporter le pire.', 'Kobe Bryant', 'Réalité', 'Discipline', 99, NULL),
  ('Ceux qui ne peuvent pas abandonner quelque chose ne peuvent jamais espérer changer quoi que ce soit.', 'Armin Arlert', 'L''Attaque des Titans', 'Ambition', 96, NULL),
  ('Un roi doit être plus avide que n''importe qui d''autre. Il doit rire plus fort et être plus en colère.', 'Rider (Iskandar)', 'Fate/Zero', 'Ambition', 98, NULL),
  ('Le monde appartient à ceux qui sont prêts à tout pour le conquérir.', 'Mads Mikkelsen', 'Réalité', 'Ambition', 92, NULL),
  ('L''effort ne trahit jamais. Mais les rêves le font souvent.', 'Hachiman Hikigaya', 'Oregairu', 'Mental', 90, NULL),
  ('Je ne reviens jamais sur ma parole. C''est ça, mon nindô !', 'Naruto Uzumaki', 'Naruto', 'Discipline', 98, NULL),
  ('Les gens vivent en s''appuyant sur leurs convictions et leurs connaissances et ils appellent cela la réalité.', 'Itachi Uchiha', 'Naruto', 'Mental', 100, NULL),
  ('Si tu ne partages pas la douleur de quelqu''un, tu ne pourras jamais le comprendre.', 'Nagato (Pain)', 'Naruto', 'Mental', 99, NULL),
  ('Un mot prononcé ne peut être repris. Un guerrier ne revient jamais sur sa parole.', 'Seiya', 'Chevaliers du Zodiaque', 'Discipline', 94, NULL),
  ('Le cosmos n''a pas de limite, seule ta volonté en a une.', 'Marine', 'Chevaliers du Zodiaque', 'Mental', 92, NULL),
  ('On ne devient pas un dieu en restant assis sur un trône.', 'Saga des Gémeaux', 'Chevaliers du Zodiaque', 'Ambition', 97, NULL),
  ('Le pouvoir n''est pas une volonté, c''est le phénomène de faire bouger les choses.', 'Madara Uchiha', 'Naruto', 'Ambition', 100, NULL),
  ('On peut toujours mourir. C''est vivre qui demande du courage.', 'Himura Kenshin', 'Kenshin le Vagabond', 'Mental', 95, NULL),
  ('Si tu as le temps de penser à une belle fin, alors vis magnifiquement jusqu''à la fin.', 'Sakata Gintoki', 'Gintama', 'Mental', 93, NULL),
  ('La peur de la mort est pire que la mort elle-même.', 'Ichigo Kurosaki', 'Bleach', 'Mental', 91, NULL),
  ('Si je recule d''un seul pas, j''ai l''impression que tous ces serments et promesses seront brisés.', 'Roronoa Zoro', 'One Piece', 'Discipline', 99, NULL),
  ('Les gens ne cessent jamais de rêver !', 'Marshall D. Teach', 'One Piece', 'Ambition', 96, NULL),
  ('Être fort ne signifie pas seulement avoir de la puissance, cela signifie avoir un cœur.', 'Shanks', 'One Piece', 'Mental', 97, NULL),
  ('Si tu veux connaître quelqu''un, cherche à savoir ce qui le met en colère.', 'Gon Freecss', 'Hunter x Hunter', 'Mental', 92, NULL),
  ('Je ne vais pas mourir. Je vais juste aller voir si je suis encore en vie.', 'Spike Spiegel', 'Cowboy Bebop', 'Mental', 98, NULL),
  ('Celui qui n''a pas de but ne trouvera jamais son chemin.', 'Isaac Netero', 'Hunter x Hunter', 'Ambition', 98, NULL),
  ('La force est la seule chose qui compte dans ce monde. Tout le reste n''est qu''illusion pour les faibles.', 'Vegeta', 'Dragon Ball Z', 'Ambition', 99, NULL),
  ('Les limites n''existent que si tu les acceptes.', 'Son Goku', 'Dragon Ball Z', 'Discipline', 97, NULL),
  ('Admire ma forme, car elle est la justice incarnée.', 'Zamasu', 'Dragon Ball Super', 'Ambition', 91, NULL),
  ('Si tu ne peux pas trouver une raison de te battre, alors tu n''as rien à faire sur un champ de bataille.', 'Kenpachi Zaraki', 'Bleach', 'Discipline', 96, NULL),
  ('Admirer quelqu''un, c''est la distance la plus éloignée de la compréhension.', 'Sosuke Aizen', 'Bleach', 'Mental', 100, NULL),
  ('Tu devrais profiter des petits détours. C''est là que tu trouveras ce qui est plus important que ce que tu cherches.', 'Ging Freecss', 'Hunter x Hunter', 'Mental', 95, NULL),
  ('La différence entre le novice et le maître est que le maître a échoué plus de fois que le novice n''a essayé.', 'Koro-sensei', 'Assassination Classroom', 'Discipline', 96, NULL),
  ('La haine est le refuge de ceux qui ne peuvent pas supporter leur propre faiblesse.', 'Jiren', 'Dragon Ball Super', 'Mental', 94, NULL),
  ('Un homme qui ne peut pas protéger ses propres rêves ne peut protéger rien du tout.', 'Crocodile', 'One Piece', 'Ambition', 95, NULL),
  ('Je ne suis pas un héros parce que je veux l''être. Je le suis parce que je n''ai pas le choix.', 'Ichigo Kurosaki', 'Bleach', 'Discipline', 91, NULL),
  ('Le talent est quelque chose que tu fais éclore, l''instinct est quelque chose que tu polis.', 'Oikawa Toru', 'Haikyuu!!', 'Discipline', 96, NULL),
  ('Qu''est-ce que la défaite ? C''est rien d''autre qu''une étape vers la victoire.', 'Ryota Kise', 'Kuroko no Basket', 'Ambition', 90, NULL),
  ('Si tu ne prends pas de risques, tu ne peux pas créer d''avenir.', 'Monkey D. Luffy', 'One Piece', 'Ambition', 97, NULL),
  ('La force ne réside pas dans ce que tu peux faire, mais dans ce que tu peux endurer.', 'Guts', 'Berserk', 'Discipline', 100, NULL),
  ('Ne compte pas les choses que tu as perdues. Demande-toi ce qu''il te reste.', 'Jinbe', 'One Piece', 'Mental', 96, NULL),
  ('La perfection est une illusion qui empêche de progresser.', 'Mayuri Kurotsuchi', 'Bleach', 'Mental', 94, NULL),
  ('Si tu veux gagner, tu dois être prêt à tout brûler, même tes souvenirs.', 'Eren Jaeger', 'L''Attaque des Titans', 'Ambition', 99, NULL),
  ('La solitude est le prix à payer pour l''excellence.', 'Itachi Uchiha', 'Naruto', 'Mental', 98, NULL),
  ('Celui qui n''a pas peur n''est pas courageux. Le courage, c''est d''agir malgré la peur.', 'All Might', 'My Hero Academia', 'Mental', 95, NULL),
  ('Il n''y a pas de raccourci pour devenir un roi.', 'Griffith', 'Berserk', 'Ambition', 98, NULL),
  ('La véritable force est de sourire quand on a envie de pleurer.', 'Nana Shimura', 'My Hero Academia', 'Mental', 93, NULL),
  ('Ne sois pas seulement une arme. Sois l''utilisateur de l''arme.', 'Musashi Miyamoto', 'Vagabond', 'Mental', 99, NULL),
  ('On ne peut pas avancer si on regarde toujours en arrière.', 'Edward Elric', 'Fullmetal Alchemist', 'Discipline', 92, NULL),
  ('Le monde est cruel, mais il est aussi très beau.', 'Mikasa Ackerman', 'L''Attaque des Titans', 'Stoïcisme', 94, NULL),
  ('Un homme ne meurt vraiment que lorsqu''il est oublié.', 'Dr. Hiriluk', 'One Piece', 'Mental', 97, NULL),
  ('La justice est une arme. Elle peut être utilisée pour faire le bien, mais elle ne peut pas sauver le monde.', 'Pain', 'Naruto', 'Stoïcisme', 98, NULL),
  ('La douleur est un signal. Elle te dit que tu es encore en vie.', 'Kaneki Ken', 'Tokyo Ghoul', 'Mental', 95, NULL),
  ('Pour surpasser un monstre, tu dois accepter d''en devenir un toi-même.', 'Erwin Smith', 'L''Attaque des Titans', 'Ambition', 99, NULL),
  ('Un sabre qui ne blesse personne n''est pas un sabre.', 'Zoro Roronoa', 'One Piece', 'Discipline', 95, NULL),
  ('L''important n''est pas de battre les autres, c''est d''être meilleur qu''hier.', 'Jigoro Kano', 'Réalité (Judo)', 'Discipline', 97, NULL),
  ('Si tu tombes, relève-toi. Si tu tombes encore, relève-toi encore.', 'Rock Lee', 'Naruto', 'Discipline', 98, NULL),
  ('La différence entre un roi et son cheval est l''instinct de combat.', 'White Ichigo', 'Bleach', 'Ambition', 97, NULL),
  ('La mort est la seule chose qui rend la vie précieuse.', 'Thorkell', 'Vinland Saga', 'Stoïcisme', 94, NULL),
  ('Si tu veux la paix, prépare la guerre.', 'Végèce', 'Réalité', 'Stoïcisme', 97, NULL),
  ('Le chaos est une échelle.', 'Petyr Baelish', 'Game of Thrones', 'Ambition', 96, NULL),
  ('Le succès est la somme de petits efforts répétés jour après jour.', 'Robert Collier', 'Réalité', 'Discipline', 94, NULL),
  ('Je suis le maître de mon destin, je suis le capitaine de mon âme.', 'William Ernest Henley', 'Réalité', 'Mental', 99, NULL),
  ('Un homme ne peut rien apprendre s''il ne sacrifie rien.', 'Edward Elric', 'Fullmetal Alchemist', 'Discipline', 96, NULL),
  ('La force ne vient pas du fait de gagner. Tes luttes développent tes forces.', 'Arnold Schwarzenegger', 'Réalité', 'Discipline', 97, NULL),
  ('Même si nous ne sommes pas nés avec un don, nous pouvons le surpasser par le travail.', 'Rock Lee', 'Naruto', 'Discipline', 100, NULL),
  ('Le monde ne se divise pas en gagnants et en perdants, mais en ceux qui apprennent et ceux qui n''apprennent pas.', 'Benjamin Barber', 'Réalité', 'Mental', 92, NULL),
  ('Si tu n''aimes pas ton destin, ne l''accepte pas.', 'Naruto Uzumaki', 'Naruto', 'Ambition', 98, NULL),
  ('Je ne m''arrêterai pas quand je serai fatigué, je m''arrêterai quand j''aurai fini.', 'David Goggins', 'Réalité', 'Discipline', 100, NULL),
  ('L''homme qui a déplacé la montagne est celui qui a commencé par enlever les petites pierres.', 'Confucius', 'Réalité', 'Discipline', 94, NULL),
  ('Plus le combat est dur, plus la victoire est belle.', 'Thomas Paine', 'Réalité', 'Ambition', 93, NULL),
  ('La haine est un endroit où l''on va quand on ne peut plus supporter la douleur.', 'Gaara', 'Naruto', 'Mental', 95, NULL),
  ('Ta survie ne dépend pas de ta force, mais de ta volonté de fer.', 'Guts', 'Berserk', 'Discipline', 99, NULL),
  ('Rien de grand ne s''est accompli sans passion.', 'Hegel', 'Réalité', 'Ambition', 94, NULL),
  ('Le futur appartient à ceux qui se préparent aujourd''hui.', 'Malcolm X', 'Réalité', 'Ambition', 96, NULL),
  ('Sois ton propre héros. Ne cherche pas quelqu''un pour te sauver.', 'All Might', 'My Hero Academia', 'Mental', 94, NULL),
  ('L''échec est l''opportunité de recommencer plus intelligemment.', 'Henry Ford', 'Réalité', 'Discipline', 91, NULL),
  ('Je préfère mourir en essayant d''atteindre mes rêves que de vivre une vie sans eux.', 'Portgas D. Ace', 'One Piece', 'Ambition', 98, NULL),
  ('Un petit pas pour l''homme, un bond de géant pour l''humanité.', 'Neil Armstrong', 'Réalité', 'Ambition', 92, NULL),
  ('La connaissance n''est pas suffisante, nous devons l''appliquer.', 'Johann Wolfgang von Goethe', 'Réalité', 'Discipline', 93, NULL),
  ('Un idéaliste est une personne qui aide les autres à être prospères.', 'Henry Ford', 'Réalité', 'Mental', 90, NULL),
  ('Le vrai pouvoir, c''est de pouvoir choisir sa propre voie.', 'Mewtwo', 'Pokémon', 'Stoïcisme', 95, NULL),
  ('Le courage, ce n''est pas l''absence de peur, mais la capacité de la vaincre.', 'Nelson Mandela', 'Réalité', 'Mental', 97, NULL),
  ('On ne peut pas changer le passé, mais on peut construire le futur.', 'Trunks', 'Dragon Ball Z', 'Mental', 93, NULL),
  ('Si tu veux connaître la fin, regarde le début.', 'Proverbe Africain', 'Réalité', 'Mental', 91, NULL),
  ('La discipline est la mère du succès.', 'Eschyle', 'Réalité', 'Discipline', 95, NULL),
  ('Ne pleure pas parce que c''est fini, souris parce que c''est arrivé.', 'Dr. Seuss', 'Réalité', 'Stoïcisme', 90, NULL),
  ('Je ne perdrai pas. Même si mon corps se brise, mon âme restera debout.', 'Saint Seiya', 'Chevaliers du Zodiaque', 'Discipline', 98, NULL),
  ('Le succès n''est pas définitif, l''échec n''est pas fatal : c''est le courage de continuer qui compte.', 'Winston Churchill', 'Réalité', 'Ambition', 97, NULL),
  ('L''action est la clé fondamentale de tout succès.', 'Pablo Picasso', 'Réalité', 'Discipline', 92, NULL),
  ('Sois le changement que tu veux voir dans ce monde.', 'Gandhi', 'Réalité', 'Stoïcisme', 96, NULL),
  ('On ne voit bien qu''avec le cœur. L''essentiel est invisible pour les yeux.', 'Antoine de Saint-Exupéry', 'Réalité', 'Mental', 91, NULL),
  ('L''homme n''est pas fait pour la défaite. Un homme peut être détruit, mais pas vaincu.', 'Ernest Hemingway', 'Réalité', 'Mental', 98, NULL),
  ('L''ignorant affirme, le savant doute, le sage réfléchit.', 'Aristote', 'Réalité', 'Stoïcisme', 95, NULL),
  ('Rien n''est plus contagieux que l''exemple.', 'François de La Rochefoucauld', 'Réalité', 'Discipline', 91, NULL),
  ('La difficulté de réussir ne fait qu''ajouter à la nécessité d''entreprendre.', 'Beaumarchais', 'Réalité', 'Ambition', 94, NULL),
  ('Le vrai bonheur est de profiter du présent sans dépendre anxieusement du futur.', 'Sénèque', 'Réalité', 'Stoïcisme', 100, NULL),
  ('On ne devient pas vieux pour avoir vécu un certain nombre d''années, on devient vieux parce qu''on a déserté son idéal.', 'Douglas MacArthur', 'Réalité', 'Ambition', 93, NULL),
  ('Le destin n''est pas une question de chance, c''est une question de choix.', 'William Jennings Bryan', 'Réalité', 'Mental', 97, NULL),
  ('Celui qui n''a pas d''ennemis n''a pas de caractère.', 'Paul Newman', 'Réalité', 'Mental', 92, NULL),
  ('Je ne cherche pas à être meilleur que les autres, je cherche à être meilleur que moi-même.', 'Mikhaïl Baryshnikov', 'Réalité', 'Discipline', 96, NULL),
  ('Là où croît le péril, croît aussi ce qui sauve.', 'Friedrich Hölderlin', 'Réalité', 'Stoïcisme', 98, NULL),
  ('La vie est soit une aventure audacieuse, soit rien du tout.', 'Helen Keller', 'Réalité', 'Ambition', 95, NULL),
  ('Un homme de caractère peut être vaincu, mais jamais découragé.', 'Lord Byron', 'Réalité', 'Mental', 96, NULL),
  ('Le travail d''un homme est le reflet de son âme.', 'Michel-Ange', 'Réalité', 'Discipline', 97, NULL),
  ('La tragédie de la vie ne réside pas dans le fait de ne pas atteindre son but, mais de ne pas avoir de but à atteindre.', 'Benjamin Mays', 'Réalité', 'Ambition', 94, NULL),
  ('L''intelligence, c''est la faculté d''adaptation au changement.', 'Stephen Hawking', 'Réalité', 'Mental', 98, NULL),
  ('Il n''y a pas de vent favorable pour celui qui ne sait pas où il va.', 'Sénèque', 'Réalité', 'Ambition', 99, NULL),
  ('L''enthousiasme est à la base de tout progrès.', 'Henry Ford', 'Réalité', 'Ambition', 91, NULL),
  ('La plus grande preuve de courage est de supporter la défaite sans perdre espoir.', 'Robert Ingersoll', 'Réalité', 'Mental', 95, NULL),
  ('Si tu veux être heureux, sois-le.', 'Léon Tolstoï', 'Réalité', 'Stoïcisme', 90, NULL),
  ('Le succès n''est pas dans ce que vous avez, mais dans ce que vous êtes.', 'Bo Bennett', 'Réalité', 'Mental', 93, NULL),
  ('Un pessimiste voit la difficulté dans chaque opportunité ; un optimiste voit l''opportunité dans chaque difficulté.', 'Winston Churchill', 'Réalité', 'Mental', 97, NULL),
  ('On peut tout enlever à un homme sauf une chose : la dernière des libertés humaines — celle de choisir son attitude.', 'Viktor Frankl', 'Réalité', 'Stoïcisme', 100, NULL),
  ('C’est par le travail que l''homme se transforme.', 'Karl Marx', 'Réalité', 'Discipline', 91, NULL),
  ('Le courage est la première des qualités humaines car elle garantit toutes les autres.', 'Aristote', 'Réalité', 'Discipline', 98, NULL),
  ('Tout obstacle renforce la détermination. Celui qui s''est fixé un but n''en change pas.', 'Léonard de Vinci', 'Réalité', 'Discipline', 99, NULL),
  ('Vivez comme si vous deviez mourir demain. Apprenez comme si vous deviez vivre toujours.', 'Mahatma Gandhi', 'Réalité', 'Mental', 98, NULL),
  ('Il n''y a qu''un luxe véritable, et c''est celui des relations humaines.', 'Antoine de Saint-Exupéry', 'Réalité', 'Stoïcisme', 90, NULL),
  ('La seule chose dont nous devons avoir peur, c''est de la peur elle-même.', 'Franklin D. Roosevelt', 'Réalité', 'Mental', 96, NULL),
  ('Pour être un champion, vous devez croire en vous-même quand personne d''autre ne le fait.', 'Sugar Ray Robinson', 'Réalité', 'Ambition', 97, NULL),
  ('La liberté commence par la maîtrise de soi.', 'Épicure', 'Réalité', 'Discipline', 98, NULL),
  ('Ce n''est pas la montagne que nous conquérons, mais nous-mêmes.', 'Edmund Hillary', 'Réalité', 'Discipline', 100, NULL),
  ('Le doute est le commencement de la sagesse.', 'René Descartes', 'Réalité', 'Mental', 94, NULL),
  ('On ne peut pas diriger le vent, mais on peut ajuster ses voiles.', 'Jim Rohn', 'Réalité', 'Stoïcisme', 95, NULL),
  ('La patience est la forme la plus haute de la force.', 'George Woodberry', 'Réalité', 'Discipline', 93, NULL),
  ('Agissez toujours comme s''il était impossible d''échouer.', 'Winston Churchill', 'Réalité', 'Ambition', 97, NULL),
  ('Soyez vous-même, tous les autres sont déjà pris.', 'Oscar Wilde', 'Réalité', 'Mental', 96, NULL),
  ('La volonté de gagner est importante, mais la volonté de se préparer est vitale.', 'Joe Paterno', 'Réalité', 'Discipline', 98, NULL),
  ('La vie ne consiste pas à se trouver, elle consiste à se créer.', 'George Bernard Shaw', 'Réalité', 'Ambition', 95, NULL),
  ('Rien de grand n''a jamais été accompli sans une certaine forme de sacrifice.', 'Napoléon Bonaparte', 'Réalité', 'Ambition', 99, NULL),
  ('Le savoir est le seul trésor que l''on peut donner sans s''en démunir.', 'Proverbe Hébreu', 'Réalité', 'Mental', 92, NULL),
  ('La clarté d''esprit signifie aussi la clarté de passion.', 'Blaise Pascal', 'Réalité', 'Mental', 94, NULL),
  ('Si vous jugez les gens, vous n''avez pas le temps de les aimer.', 'Mère Teresa', 'Réalité', 'Stoïcisme', 91, NULL),
  ('La force est de pouvoir rompre un morceau de chocolat en quatre et de n''en manger qu''un carré.', 'Judith Viorst', 'Réalité', 'Discipline', 90, NULL),
  ('Je n''ai jamais échoué. J''ai simplement trouvé 10 000 solutions qui ne fonctionnaient pas.', 'Thomas Edison', 'Réalité', 'Discipline', 98, NULL),
  ('L''action est le remède à la peur.', 'Jean-Paul Sartre', 'Réalité', 'Mental', 95, NULL),
  ('Ne comptez pas les jours, faites que chaque jour compte.', 'Muhammad Ali', 'Réalité', 'Discipline', 99, NULL),
  ('Pour réaliser de grandes choses, il faut d''abord y croire.', 'Steve Jobs', 'Réalité', 'Ambition', 97, NULL);
